defaults:
  - /comat/model/sd21@model
  - /comat/dataset/gan_data@dataset
  - /comat/trainer/trainer@trainer
  - _self_

dataset:
  training_prompts: "./data/train_data_sd21/gan_train_data.jsonl"

seed: 995